title: Lucas Tavares Brito
url: "https://lucastbrito.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Atuação Profissional"
   link: "profissional"
 - name: "Educação"
   link: "educacao"
 - name: "Projetos Executados"
   link: "projetos"
